I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 3, in script call
    call s0
  File "game/script/Season0/season0.rpy", line 8, in script call
    call s0s45
  File "game/script/Season0/s0s45.rpy", line 57, in script
    hide akina fear with pixe
  File "game/script/Season0/s0s45.rpy", line 57, in <module>
    hide akina fear with pixe
NameError: name 'pixe' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 3, in script call
    call s0
  File "game/script/Season0/season0.rpy", line 8, in script call
    call s0s45
  File "game/script/Season0/s0s45.rpy", line 57, in script
    hide akina fear with pixe
  File "C:\Users\Tingxuan\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1674, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\Tingxuan\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Tingxuan\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script/Season0/s0s45.rpy", line 57, in <module>
    hide akina fear with pixe
NameError: name 'pixe' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Project StaRS 1.0
Fri Dec  8 17:29:36 2023
